# Day 20/180 

# Numpy Fundamentals 

- What is NumPy and why it exists
- NumPy arrays vs Python lists
- Creating arrays with `np.array()`  
- Creating sequences with `np.arange()`
- Creating evenly spaced values with `np.linspace()`
- `arange()` vs `linspace()`
- Basic array properties: `ndim`, `shape`, `size`, `dtype`
- Basic NumPy arithmetic
- Creating identity matrices with `np.eye()`

## What is Numpy?

Numpy stand for **Numerical Python**.

- Python library for numerical and scientific computing.
- It's main data structure is the **NumPy array (`ndarray`)**.
- It is designed to work efficiently with large amounts of numerical data.
- It supports fast mathematical operations on entire arrays.
- NumPy is widely used in data science, machine learning, cybersecurity, scientific computing, and statistics etc.


In [1]:
import numpy as np 

In [2]:
numbers = np.array([10, 20, 30, 40])
print(numbers)

[10 20 30 40]


In [3]:
numbers = np.array([1, 2, 3])

print(numbers + 10)
print(numbers * 2)
print(numbers ** 2)

[11 12 13]
[2 4 6]
[1 4 9]


In [4]:
import numpy as np
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## NumPy Arrays vs Python Lists

### NumPy Array
- Designed mainly for numerical data.
- Usually stores elements using a common data type.
- Arithmetic operations work element-by-element.
- Supports vectorized operations and broadcasting.
- More efficient for large numerical calculations.

### Python List
- General-purpose collection.
- Can contain different data types.
- `+` joins lists together.
- `*` repeats a list.

In [5]:
# NumPy array

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)

[5 7 9]


In [6]:
# NumPy multiplication

numbers = np.array([1, 2, 3])
print(numbers * 3)

[3 6 9]


In [7]:
# Python list

x = [1, 2, 3]
y = [4, 5, 6]
print(x + y)

[1, 2, 3, 4, 5, 6]


In [8]:
# List multiplication

numbers = [1, 2, 3]
print(numbers * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


## Creating Arrays with `np.array()`

`np.array()` converts Python sequences such as lists into NumPy arrays.

- We Can create 1D, 2D, and higher-dimensional arrays.
- Arrays can contain integers, floats, strings, etc.
- Numerical arrays normally use a common data type.

In [9]:
# 2D array

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [10]:
# 3D array  these are also knows as tensors

arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


We can also specify data types.

In [11]:
numbers = np.array([1, 2, 3], dtype=float)

print(numbers)
print(numbers.dtype)

[1. 2. 3.]
float64


In [12]:
numbers = np.array([1, 2, 3], dtype=bool)

print(numbers)
print(numbers.dtype)

[ True  True  True]
bool


## Important NumPy Array Properties

### `ndim`
Returns the number of dimensions.

### `shape`
Returns the size of each dimension.

### `size`
Returns the total number of elements.

### `dtype`
Returns the data type of the elements.

In [13]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

2
shape: (2, 3)
size: 6
dtype: int64


In [14]:
arr = np.array([11, 22, 33])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(3,)
3
int64


## NumPy Array Arithmetic

NumPy performs arithmetic **element-by-element**.

In [15]:
# element-wise 

x = np.array([10, 20, 30])
y = np.array([2, 4, 5])

print("Addition:", x + y)
print("Subtraction:", x - y)
print("Multiplication:", x * y)
print("Division:", x / y)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [16]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


### Broadcasting

In numpy, broadcasting is a technique where you can perform operations on different data types without manually copying and reshaping the data types in many cases.

In [17]:
import numpy as np

x = np.array([1, 2, 3])
print(x + 10)   # here 10 is a scalar. NumPy conceptually broadcasts 10 across all elements:

[11 12 13]


In [18]:
# with 2D array
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [19]:
print(b.shape)

(3,)


In [20]:
# with 3D array

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [21]:
# with 3D array

arr = np.array([
    [
        [12, 13], 
        [23, 24]
        ], 
        [
            [15, 16], 
            [27, 28]]])

print(arr)
print(arr.ndim)
print(arr.shape)

[[[12 13]
  [23 24]]

 [[15 16]
  [27 28]]]
3
(2, 2, 2)


## Creating Arrays with `np.arange()`

`np.arange()` used tp create a sequence of numbers.

### Syntax
```python
np.arange(start, stop, step)

start : included
stop : excluded
step : gap between values

In [22]:
print(np.arange(2, 8))

[2 3 4 5 6 7]


In [23]:
print(np.arange(0, 15, 3))

[ 0  3  6  9 12]


In [24]:
print(np.arange(0, 20, 2.5))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5]


In [25]:
print(np.arange(10, 0, -1))

[10  9  8  7  6  5  4  3  2  1]


## Creating Arrays with `np.linspace()`

`np.linspace()` creates evenly spaced numbers.

### Syntax
```python
np.linspace(start, stop, num)

start : starting value
stop : ending value
num :  It specifies how many values to create.

Inshort means linspace control the number of points.

In [26]:
print(np.linspace(10, 20, 3))

[10. 15. 20.]


In [27]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [28]:
print(np.linspace(20, 40, 12))

[20.         21.81818182 23.63636364 25.45454545 27.27272727 29.09090909
 30.90909091 32.72727273 34.54545455 36.36363636 38.18181818 40.        ]


## Main difference

arange() : specify the step

linspace() : specify the number of values

## Identity Matrix with `np.eye()`

An identity matrix is a square matrix where:

- Main diagonal contains `1`.
- All other elements contain `0`.
- It has the same number of rows and columns.

In [29]:
print(np.eye(2))

[[1. 0.]
 [0. 1.]]


In [30]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
