# Day 21/180  

## NumPy: Ones, Zeros & Array Operations

- `np.ones()` and `np.zeros()`
- Array operations
- `max()`, `min()`, `sum()`, `prod()`
- `mean()` and `median()`
- Standard deviation
- Variance
- `axis=0` and `axis=1`

## np.zeros() and np.ones()

### np.zeros()

creates an array where every element is 0.

### np.ones()

creates an array where every element is 1.

**Imp:** np.zeros and np.ones are used to initialize the values.

In [1]:
import numpy as np

In [12]:
a = np.zeros(6)
print(a)

[0. 0. 0. 0. 0. 0.]


In [14]:
a = np.zeros((4, 6))
print(a)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
import numpy as np 
a = np.ones(3)
print(a)

[1. 1. 1.]


In [10]:
x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [9]:
x = np.ones((3, 5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
a = np.ones((3, 4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Array Operations

There are two types of operations:
- Scalar operation
- Vector operation

### Scalar Operation
In scalar operation, we can operate with single number. e.g a + 5 here 5 is scalar.

### Vector Operation 
In vector opertion, we can apply any operation on two numpy arrays. 
e.g a1 + a2

In [16]:
a = np.array([1, 2, 3, 4, 5])
print(a + 5)

[ 6  7  8  9 10]


In [17]:
a = np.array([11, 14, 16, 18])
print(a ** 3)

[1331 2744 4096 5832]


In [18]:
a = np.array([11, 14, 16, 18])
print(a * 3)

[33 42 48 54]


In [19]:
a1 = np.array([12, 14, 16, 18])
a2 = np.array([10, 20, 30, 40])
print(a1 + a2)
print(a1 * a2)
print(a1 ** a2)
print(a1 - a2)

[22 34 46 58]
[120 280 480 720]
[         61917364224 -6175693061724569600                    0
  8778713041907744768]
[  2  -6 -14 -22]


## np.max() and np.min()

### np.max()
find the largest value

### np.min()
find the smallest value

In [20]:
numbers = np.array([10,20, 30, 40, 50])
print(np.max(numbers))
print(np.min(numbers))

50
10


Here 0 shows column and 1 show rows.

In [23]:
a1 = np.array([12, 14, 16, 18])
a2 = np.array([10, 20, 30, 40])

print(np.max(a1, axis=0))
print(np.min(a2, axis=0))

18
10


In [26]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6]
])
print(np.max(a, axis=0))
print(np.min(a, axis=1)) 

[4 5 6]
[1 4]


In [27]:
a = np.array([
    [11, 2, 33], 
    [14, 55, 6]
])
print(np.max(a, axis=0))
print(np.min(a, axis=1)) 

[14 55 33]
[2 6]


In [30]:
a = np.array([[
    [1, 2, 3],
    [4, 5, 6]
],
[
    [7, 8, 9],
    [10, 11, 12]
]])

print(np.min(a))

1


In [31]:
a = np.array([[
    [1, 2, 3],
    [4, 5, 6]
],
[
    [7, 8, 9],
    [10, 11, 12]
]])

print(np.max(a))

12


In [33]:
print(np.min(a, axis=0))
print(np.min(a, axis=1))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [7 8 9]]


In [34]:
print(np.max(a, axis=0))
print(np.max(a, axis=1))

[[ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [10 11 12]]


## np.sum()

add all elements together.

In [35]:
a = np.array([1, 2, 3, 4, 5])
print(np.sum(a))
print(np.sum(a, axis=0))

15
15


In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))

21


In [37]:
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


## np.prod()

Here prod means product. It multiplies all elements together.


In [38]:
numbers = np.array([11, 12, 13])
print(np.prod(numbers))

1716


In [39]:
numbers = np.array([10, 20, 30])
print(np.prod(numbers))

6000


## mean() and median()

### mean() 

Means is the average

**formula: sum of value / no of value**

### median()

Middle value after the data has been arraanged in the sorted order.

If there is an even number of values, the median is the average of the two middle values.

In [40]:
numbers = ([10, 20, 30, 40, 50, 60])
print(np.mean(numbers))
print(np.median(numbers))

35.0
35.0


In [41]:
numbers = ([11, 23, 30, 47, 50, 60])
print(np.mean(numbers))
print(np.median(numbers))

36.833333333333336
38.5


In [42]:
a = np.array([[11, 13, 17], [21, 24, 28]])
print(np.mean(a))
print(np.median(a))
print(np.mean(a, axis=0))
print(np.median(a, axis=0))

19.0
19.0
[16.  18.5 22.5]
[16.  18.5 22.5]


In [43]:
print(np.mean(a, axis=1))
print(np.median(a, axis=1))

[13.66666667 24.33333333]
[13. 24.]


## Standard Deviation

Tells us about the spread of values around the mean.
- Small standard deviation : values are closer together.
- Large standard deviation : values are more spread out.

In [44]:
a = np.array([10, 13, 18, 20])
print(np.std(a))

3.960744879438715


In [45]:
a = np.array([[10, 13, 18, 20], [21, 17, 19, 12]])
print(np.std(a))


3.799671038392666


In [46]:
print(np.std(a, axis=0))
print(np.std(a, axis=1))

[5.5 2.  0.5 4. ]
[3.96074488 3.34477204]


## Variance 

Variance is another measure of how spread out data is around its mean.

In [47]:
numbers = np.array([10, 10, 10, 10])
print(np.var(numbers))

0.0


In [48]:
numbers = np.array([1, 2, 3, 4, 5])
print(np.var(numbers))

2.0


In [ ]:
# overall operations
data = np.array([12, 18, 25, 30, 15, 20, 35, 55])

print("Maximum:", np.max(data))
print("Minimum:", np.min(data))
print("Sum:", np.sum(data))
print("Product:", np.prod(data))
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))

Maximum: 55
Minimum: 12
Sum: 210
Product: 93555000000
Mean: 26.25
Median: 22.5
Standard deviation: 13.016816046944813
Variance: 169.4375


## `axis` in NumPy

When working with a 2D array, functions such as `sum()`, `mean()`, `max()`, and `min()` can operate along an axis.

For a 2D array:

- `axis=0` : operate down the rows and get a result for each column.
- `axis=1` : operate across the columns and get a result for each row.

This is very important when working with datasets.

In [51]:
marks = np.array([
    [80, 90, 70],
    [60, 75, 85]
])

print(marks)
print(np.sum(marks, axis=1))
print(np.sum(marks, axis=0))
print(np.min(marks, axis=1))
print(np.min(marks, axis=1))
print(np.max(marks, axis=1))
print(np.max(marks, axis=1))

[[80 90 70]
 [60 75 85]]
[240 220]
[140 165 155]
[70 60]
[70 60]
[90 85]
[90 85]
