# Day 22 — Indexing, Iteration & Reshaping with NumPy

- Advanced indexing
- 2D indexing and slicing
- Fancy/integer indexing
- Boolean indexing
- Multiple conditions
- Iteration
- `np.nditer()`
- `reshape()`
- `transpose()` and `.T`
- `ravel()`

## Advanced Indexing

Advanced indexing allows us to select specific elements, rows, columns, or values that satisfy a condition.

For a 2D array, the basic pattern is:

`array[row, column]`

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)
print(a.shape)

[0 1 2 3 4 5]
(6,)


In [3]:
print(a[1])

1


In [4]:
print(a[2])

2


In [5]:
print(a[-1])

5


In [6]:
print(a[-3])

3


In [7]:
print(a[-4])

2


In [8]:
print(a[4])

4


In [9]:
print(a[-5])

1


### Row and Column Indexing

For a 2D array:

- `array[row, column]` : one element
- `array[row, :]` : complete row
- `array[:, column]` : complete column

In [10]:
# 2D array
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)
print(arr.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


In [11]:
print(arr[0, 1])

20


In [12]:
print(arr[0, -1])

30


In [13]:
print(arr[1, 2])

60


In [14]:
print(arr[:, 0])
print(arr[:, 1])
print(arr[:, 2])

[10 40 70]
[20 50 80]
[30 60 90]


In [15]:
print(arr[0, :])

[10 20 30]


### 3D Indexing

In [16]:
arr = np.array([[
    [1, 2, 3],
    [4, 5, 6]
],
[ 
    [7, 8, 9],
    [10, 11, 12]
]
])

In [17]:
print(arr.shape)

(2, 2, 3)


In [18]:
print(arr[0, 1, 1])

5


In [19]:
print(arr[1, 0, -1])

9


In [20]:
print(arr[1, 1, 2])

12


In [21]:
print(arr[1, 1, -2])

11


## 2D Slicing

I can select a range of rows and columns using:

`array[row_start:row_stop, column_start:column_stop]`

The stop index is not included.

In [22]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[1:2])
print(arr[0:2])

[[40 50 60]]
[[10 20 30]
 [40 50 60]]


In [23]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0:2, 1:3])
print(arr[1: , 0:2])

[[20 30]
 [50 60]]
[[40 50]
 [70 80]]


In [24]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[:, 0:2])
print(arr[:, 1:2])

[[10 20]
 [40 50]
 [70 80]]
[[20]
 [50]
 [80]]


In [25]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[1:, 1:])

[[50 60]
 [80 90]]


In [26]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[2, 0:2])

[70 80]


In [27]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[2:, 2:3])
print(arr[1:, 1:2])
print(arr[1:, 1:2])

[[90]]
[[50]
 [80]]
[[50]
 [80]]


In [28]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[1:2, 2:3])

[[60]]


In [29]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[2:3, 2:3])

[[90]]


In [30]:
print(arr[2:, 1:2])

[[80]]


In [31]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0:1, 0:1])
print(arr[0:2, :2])
print(arr[0:1, 1:2])
print(arr[0:1, 2:3])

[[10]]
[[10 20]
 [40 50]]
[[20]]
[[30]]


In [32]:
print(arr[:, ::2])

[[10 30]
 [40 60]
 [70 90]]


In [33]:
print(arr[::-1])

[[70 80 90]
 [40 50 60]
 [10 20 30]]


## Fancy / Integer Indexing

Fancy indexing means using a list or array of indexes to select specific elements.

Unlike normal slicing, you can select non-consecutive positions.

In [34]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers[[0, 2, 4]])
print(numbers[[1, 3]])
print(numbers[[0, 0, 1, 1, 2, 3, 3]])

[10 30 50]
[20 40]
[10 10 20 20 30 40 40]


In [35]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[[0, 2]]) #selecting 0 and row 2
print(arr[[1]])  #selecting row 1
print(arr[[0, 1, 2], [0, 1, 2]])   #selecting specific elements

[[10 20 30]
 [70 80 90]]
[[40 50 60]]
[10 50 90]


The expression:

`arr[[0, 1, 2], [0, 1, 2]]`

pairs the row and column indexes:

- `(0, 0)` : `10`
- `(1, 1)` : `50`
- `(2, 2)` : `90`

So the result is `[10 50 90]`

In [36]:
print(arr[[0,1], [0,1]])

[10 50]


In [37]:
print(arr[[0], [2]])

[30]


In [38]:
print(arr[[1], [0]])

[40]


## Boolean Indexing

Boolean indexing selects elements based on a condition.

NumPy first creates `True` and `False` values, then uses them to select matching elements.

In [39]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers > 25)
print(numbers[numbers > 25])
print(numbers[numbers < 35])

[False False  True  True  True]
[30 40 50]
[10 20 30]


In [40]:
# 2D, here condition is checked against every element
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[arr > 50])
print(arr[arr < 30])
print(arr[arr == 40])

[60 70 80 90]
[10 20]
[40]


### Multiple Conditions

For NumPy arrays:

- `&` means AND
- `|` means OR
- `~` means NOT

Each condition should normally be placed inside parentheses.

In [41]:
numbers = np.array([10, 20, 30, 40, 50, 60])
result = numbers[(numbers > 20) & (numbers < 50)]
print(result)

[30 40]


In [42]:
result = numbers[(numbers > 20) | (numbers < 50)]
print(result)

[10 20 30 40 50 60]


In [43]:
result = numbers[(numbers == 20) | (numbers < 50)]
print(result)

[10 20 30 40]


In [44]:
result = numbers[~(numbers > 30)]
print(result)

[10 20 30]


### Important

For NumPy arrays, use:

`&` : AND  
`|` : OR  
`~` : NOT

Do not normally use Python's `and`, `or`, and `not` for element-wise NumPy conditions.

Boolean indexing can also be used to change values that satisfy a condition.

In [45]:
numbers = np.array([10, 20, 30, 40, 50])
numbers[numbers > 30] = 0
print(numbers)

[10 20 30  0  0]


In [46]:
numbers = np.array([10, 20, 30, 40, 50])
numbers[numbers <= 30] = 0
print(numbers)

[ 0  0  0 40 50]


In [47]:
numbers = np.array([1, 2, 3, 4, 5, 6])
numbers[numbers % 2 == 0] = 100
print(numbers)

[  1 100   3 100   5 100]


In [48]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[arr > 50] = -1
print(arr)

[[10 20 30]
 [40 50 -1]
 [-1 -1 -1]]


In [49]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[arr >= 50] = -1
print(arr)

[[10 20 30]
 [40 -1 -1]
 [-1 -1 -1]]


In [50]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

arr[arr <= 50] = -1

print(arr)

[[-1 -1 -1]
 [-1 -1 60]
 [70 80 90]]


## Iteration

Iteration means going through the elements of an array one by one.

A 1D array can be directly used in a `for` loop.

In [51]:
numbers = np.array([0, 1, 2, 3, 4, 5])

for value in numbers:
    print(value)

0
1
2
3
4
5


In [52]:
for value in numbers:
    print(value * 2)

0
2
4
6
8
10


In [53]:
for value in numbers:
    print(value ** 2)

0
1
4
9
16
25


During iterating over a 2D array, NumPy gives one row at a time.

In [54]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [55]:
for row in arr:
    for value in row:
        print(value)

1
2
3
4
5
6


## `np.nditer()`

`np.nditer()` allows us to iterate through every element of an array, even when the array has multiple dimensions.

In [56]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

for value in np.nditer(arr):
    print(value)

1
2
3
4
5
6


In [57]:
# 3D array
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

for value in np.nditer(arr):
    print(value)

1
2
3
4
5
6
7
8


## Reshaping Arrays

`reshape()` changes the shape of an array without changing the number of elements.

The total number of elements must remain the same.

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [59]:
new_arr = arr.reshape(2, 3)
print(new_arr)
print(new_arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [60]:
new_arr = arr.reshape(3, 2)
print(new_arr)
print(new_arr.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [61]:
new_arr = arr.reshape(1, 6)
print(new_arr)
print(new_arr.shape)

[[1 2 3 4 5 6]]
(1, 6)


### Reshape Rule

The total number of elements must remain the same.

For 6 elements:

- `2 × 3 = 6` : valid
- `3 × 2 = 6` : valid
- `1 × 6 = 6` : valid
- `6 × 1 = 6` : valid

But `2 × 4 = 8`, so `reshape(2, 4)` is invalid.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))
print(arr.reshape(3, 2))
print(arr.reshape(1, 6))
print(arr.reshape(6, 1))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))
print(arr.reshape(4, 2))
print(arr.reshape(1, 8))
print(arr.reshape(8, 1))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Transpose

Transpose changes rows into columns and columns into rows.

In [64]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [65]:
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


## `ravel()`

`ravel()` converts an array into a one-dimensional array.

It is useful when you want to flatten a multidimensional array into a single sequence of values.

In [66]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ravel())

[1 2 3 4 5 6]


In [67]:
result = arr.ravel()
print(result)
print(result.shape)

[1 2 3 4 5 6]
(6,)


In [68]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr.ravel())

[1 2 3 4 5 6 7 8]
