# Day 23 — NumPy: Stacking, Concatenation & Splitting

- `np.stack()`
- `np.vstack()`
- `np.hstack()`
- `axis`
- `np.concatenate()`
- `np.split()`
- `np.vsplit()`
- `np.hsplit()`
- `np.column_stack()`

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a)
print(b)

[1 2 3]
[4 5 6]


## `stack()`

`np.stack()` combines multiple arrays into a new dimension.

In [13]:
a = np.array([11, 22, 33])
b = np.array([44, 55, 66])

result = np.stack((a, b))
print(result)
print(result.shape)

[[11 22 33]
 [44 55 66]]
(2, 3)


In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.stack((a, b, c), axis=0)

print(result)
print(result.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


## `np.vstack()` - Vertical Stacking

`vstack()` means vertical stacking.

It places one array below another.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# The arrays become rows of a new 2D array.

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [5]:
print(result.shape)

(2, 3)


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.vstack((a, b, c))
print(result)
print(result.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### `vstack()` With 2D Arrays

`vstack()` can also combine existing 2D arrays.

When stacking vertically:
- rows are added
- columns must be compatible

In [7]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.vstack((a, b))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
print(result.shape)

(4, 2)


### Understanding the Shape of `vstack()`

Suppose:

A = `(2, 3)`
B = `(4, 3)`

When using `vstack()`:

rows are added:

2 + 4 = 6

columns remain:

3

So the result becomes: (6, 3)

In [9]:
a = np.zeros((2, 3))
b = np.ones((4, 3))

result = np.vstack((a, b))

print(a.shape)
print(b.shape)
print(result.shape)

(2, 3)
(4, 3)
(6, 3)


## `np.hstack()` — Horizontal Stacking

`hstack()` means horizontal stacking. It combines arrays from left to right.

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


### `hstack()` With 2D Arrays

With 2D arrays, `hstack()` adds columns.

In [11]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.hstack((a, b))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [12]:
print(result.shape)

(2, 4)


## Important Point

`vstack()` add rows and `hstack()` add columns.

## `axis`

`axis` tells NumPy which dimension an operation should work along.

For a 2D array:

- `axis=0` : first dimension
- `axis=1` : second dimension

A simple way:

axis=0 : down the rows

axis=1 : across the columns


In [14]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
print(np.sum(arr, axis=0))  #column

[12 15 18]


In [ ]:
print(np.sum(arr, axis=1))   #rows

[ 6 15 24]


In [18]:
result = np.stack((arr), axis=0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

result = np.stack((a, b, c), axis=0)

print(result)
print(result.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


### Important idea

`concatenate()` : existing axis

`stack()` : new axis

## `np.concatenate()`

`np.concatenate()` joins arrays along an existing axis.

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)
print(result.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
# 2D array 
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

result = np.concatenate((a, b), axis=0)  # joins rows
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


`axis=0` : join rows

`axis=1` : join columns

In [23]:
result = np.concatenate((a, b), axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
print(result.shape)

(2, 4)


## `stack()` vs `concatenate()`

`concatenate()` joins arrays along an existing axis.

`stack()` creates a new axis.

Example:

A shape → `(3,)`
B shape → `(3,)`

Concatenate:

`(3,) + (3,) → (6,)`

Stack:

`(3,) + (3,) → (2, 3)`

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

concatenated = np.concatenate((a, b))
stacked = np.stack((a, b))

print(concatenated)
print(stacked)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [26]:
print(concatenated.shape)

(6,)


In [27]:
print(stacked.shape)

(2, 3)


## Splitting Arrays

Splitting is the opposite idea of combining.

Stacking:

small arrays → larger array

Splitting:

large array → smaller arrays

The main functions are:

- `np.split()`
- `np.vsplit()`
- `np.hsplit()`

## `np.split()`

`np.split()` divides an array into a specified number of equal parts.

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

[1 2 3 4 5 6 7 8]


In [30]:
parts = np.split(arr, 4)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [32]:
print(parts[0])
print(parts[1])
print(parts[2])
print(parts[-1])

[1 2]
[3 4]
[5 6]
[7 8]


In [34]:
arr = np.array([1, 2, 3, 4, 5, 6])

parts = np.split(arr, 3)

for part in parts:
    print(part)

[1 2]
[3 4]
[5 6]


### Splitting at Specific Positions

We can also specify positions where the array should be split.

Example:

`np.split(arr, [2, 4])`

This creates cuts at positions 2 and 4.

In [35]:
arr = np.array([10, 20, 30, 40, 50, 60])

parts = np.split(arr, [2, 4])

for part in parts:
    print(part)

[10 20]
[30 40]
[50 60]


In [36]:
arr = np.array([10, 20, 30, 40, 50, 60])

parts = np.split(arr, [1, 4])

for part in parts:
    print(part)

[10]
[20 30 40]
[50 60]


## `np.vsplit()` — Vertical Splitting

`vsplit()` splits a 2D array by rows.

In [37]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

parts = np.vsplit(arr, 2)
print(parts)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [38]:
for part in parts:
    print(part)
    print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]



In [40]:
parts = np.vsplit(arr, 4)

for part in parts:
    print(part)
    print()

[[1 2]]

[[3 4]]

[[5 6]]

[[7 8]]



## `np.hsplit()` — Horizontal Splitting

`hsplit()` splits a 2D array by columns.

The columns are divided into separate arrays.

In [41]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

parts = np.hsplit(arr, 2)
print(parts)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [42]:
for part in parts:
    print(part)
    print()

[[1 2]
 [5 6]]

[[3 4]
 [7 8]]



In [43]:
parts = np.hsplit(arr, 4)

for part in parts:
    print(part)
    print()

[[1]
 [5]]

[[2]
 [6]]

[[3]
 [7]]

[[4]
 [8]]



### `np.split()` With `axis`

We can also control the splitting direction using `axis`.

`axis=0` → split rows

`axis=1` → split columns

In [44]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

parts = np.split(arr, 2, axis=0)

for part in parts:
    print(part)
    print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]



In [45]:
arr = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

parts = np.split(arr, 2, axis=1)

for part in parts:
    print(part)
    print()

[[1]
 [3]
 [5]
 [7]]

[[2]
 [4]
 [6]
 [8]]



## `vsplit()` vs `hsplit()`

`vsplit()` → separates rows

`hsplit()` → separates columns

## `np.column_stack()`

`column_stack()` is useful when we have separate 1D arrays
and want to turn them into columns.

For example:

names → column 1

ages → column 2

marks → column 3

In [46]:
names = np.array(["Alex", "John", "Jiang"])
ages = np.array([20, 21, 22])
marks = np.array([80, 90, 75])

result = np.column_stack((names, ages, marks))
print(result)

[['Alex' '20' '80']
 ['John' '21' '90']
 ['Jiang' '22' '75']]


In [47]:
print(result.shape)

(3, 3)


# Numpy array with Python lists

In [4]:
# list (speed)

a = [i for i in range(10000000)]
b = [i for i in range(10000000, 20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time()-start)

3.761977434158325


Numpy used C type array that is a static array means its size is fixed and the second is it's not a referential array means we can directly store items in the memory no tthe addres.
Meanwhile python list has two problems. First one is it is a dynamic array means everytime it's size increased, that takes time. 2nd is it a referential array means we can directly store memory firstly we store their address then we find items in the memory of these addresses. so in these things it take additional time.

That's why Numpy is faster than list

In [7]:
# numpy (speed) numpy used static array()

import numpy as np
a = np.arange(10000000)
b = np.arange(10000000)

start = time.time()
c = a + b
print(time.time()-start)

0.24658823013305664


In [ ]:
# list (memory)

a = [i for i in range(10000000)]
import sys   #sys is a system

sys.getsizeof(a)

89095160

In [9]:
# numpy memory 
a  = np.arange(10000000)
sys.getsizeof(a)

80000112

In [11]:
# you can also change the size 
a  = np.arange(10000000, dtype=np.int32)
sys.getsizeof(a)

40000112

In [12]:
a  = np.arange(10000000, dtype=np.int16)
sys.getsizeof(a)

20000112

In [13]:
a  = np.arange(10000000, dtype=np.int8)
sys.getsizeof(a)

10000112