# Day 25/180 — Mathematical Operations & Missing Values

- Custom Mathematical Functions
- Sigmoid Function
- Mean Squared Error (MSE)
- Missing Values (`NaN`)
- Detecting and Removing `NaN`
- Handling `NaN` in Calculations

# Custom Mathematical Operations
Numpy allows us to perform custom mathematical operations on an entire array at once. We have no need to write a for loop for every calcultion.

In [1]:
import numpy as np

If you want to find y = 2x+5 

In [2]:
x = np.array([1, 2, 3, 4, 5])
y = 2 * x + 5
print(y)

[ 7  9 11 13 15]


In [3]:
y = 2 ** x +5
print(y)

[ 7  9 13 21 37]


In [4]:
y = x ** 2 + 2 * x + 5
print(y)

[ 8 13 20 29 40]


We can use some other functions also.

In [5]:
# find square root
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [6]:
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [7]:
print(np.log(x))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [8]:
print(np.abs(x))  #find absolute value

[1 2 3 4 5]


In [9]:
print(np.sin(x)) #sine

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [10]:
print(np.cos(x))  #cosine

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [11]:
print(np.tan(x)) #tangent

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [12]:
print(np.round(x))

[1 2 3 4 5]


In [13]:
print(np.round(x))   #round values

[1 2 3 4 5]


In [14]:
print(np.ceil(x))   # round upward

[1 2 3 4 5]


In [15]:
x = np.array([1.5, 2.5, 4.5])
print(np.floor(x))  # round downward

[1. 2. 4.]


# Sigmoid Function

Mathematical function that convert any number in to a value between 0 and 1.
It used in Machine Learning(ML), especially for binary classification.

Formula:

σ(x) = 1 / (1 + e⁻ˣ)

In [16]:
x = np.array([10, 30, 50, 70, 90])
print(1/(1 + np.exp(-x)))     #sigmoid function

[0.9999546 1.        1.        1.        1.       ]


We can apply the sigmoid function to an entire array at once.

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [18]:
x = np.array([200, 300, 400, 500])
result = sigmoid(x)
print(result)

[1. 1. 1. 1.]


In [19]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
result = sigmoid(x)
print(result)

[0.04742587 0.11920292 0.26894142 0.5        0.73105858 0.88079708
 0.95257413]


In [20]:
# 2D array

x = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

result = sigmoid(x)
print(result)

[[0.9999546 1.        1.       ]
 [1.        1.        1.       ]
 [1.        1.        1.       ]]


# Mean Square Error

Method used to measure how predicted values are far from the actual values.

Formula:

MSE = (1/n) × Σ(actual - predicted)²

Where:

- `actual` = actual values
- `predicted` = predicted values
- `n` = number of values

The errors are squared before taking their average.

In [21]:
actual = np.array([10, 20, 30])
predicted = np.array([12, 18, 29])

mse = np.mean((actual - predicted)**2)

print(mse)

3.0


In [22]:
actual = np.array([122, 324, 520])
predicted = np.array([126, 328, 530])

mse = np.mean((actual - predicted)**2)

print(mse)

44.0


Imp:

- Smaller MSE means predictions are closer to the actual values.
- Larger MSE means predictions are farther away from actual values

In [23]:
def mse(actual, predicted):
    return np.mean((actual - predicted) ** 2)

In [24]:
actual = np.array([10, 20, 30])
predicted = np.array([12, 19, 28])

print(mse(actual, predicted))

3.0


In [25]:
# 2D 
actual = np.array([
    [10, 20, 30]<
    [40, 50, 60]
])

predicted = np.array([
    [70, 80, 90],
    [100, 110, 120]
])

print(mse(actual, predicted))

9127.666666666666


# Missing Values

Numpy represent missing values using NaN, means not a number.

`np.nan`

In [26]:
a = np.array([10, 20, 30, np.nan, np.nan, 40, 50])
print(a[0])
print([1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])

10.0
[1]
30.0
nan
nan
40.0


## `np.isnan()`

We can also detect nan values in numpy by using `np.isnan()`. It checks every element and returns True and False.
Here:
- True means Value is Nan 
- Falso means Value is not Nan

In [27]:
a = np.array([10, 20, 30, np.nan, np.nan, 40, 50])
result = np.isnan(a)
print(result)

[False False False  True  True False False]


We can also count missing values. Use `np.sum()` to count the True values

In [28]:
a = np.array([10, 20, 30, np.nan, np.nan, 40, 50])
count = np.sum(np.isnan(a))
print(count)

2


In [29]:
a = np.array([10, np.nan, np.nan, np.nan, np.nan, 40, 50])
count = np.sum(np.isnan(a))
print(count)

4


### `np.where()`

we can also find the position of Nan. Use `np.where()` together with `np.isnan()`

In [30]:
a = np.array([10, np.nan, np.nan, np.nan, np.nan, 40, 50])
positions = np.where(np.isnan(a))
print(positions)

(array([1, 2, 3, 4]),)


In [31]:
a = np.array([
    [10, np.nan, np.nan],
    [np.nan, np.nan, 40]
])
count = np.sum(np.isnan(a))
print(count)

4


# Ways to handle NaN Values

There are three common ways to handle NaN values.
- remove NaN  : We remove NaN by using boolean indexing.
- ignore Nan during Calculation
- replace NaN

In [32]:
# remove NaN
a = np.array([10, 20, 30, np.nan, 50])
print(a[~np.isnan(a)])

[10. 20. 30. 50.]


In [33]:
a = np.array([
    [10, 20, np.nan],
    [40, np.nan, 60]
])

print(a[~np.isnan(a)])

[10. 20. 40. 60.]


In [34]:
# ignore NaN during calculations
a = np.array([10, 20, 30, np.nan, 50])
print(np.nanmean(a))

27.5


In [35]:
a = np.array([10, 20, 30, np.nan, 50])
print(np.nanmedian(a))

25.0


In [36]:
a = np.array([10, 20, 30, np.nan, 50])
print(np.nanvar(a))

218.75


In [37]:
# replace nan: we can replace nan according to the situation(mean according to dataset)
a = np.array([10, 20, 30, np.nan, 50])
print(np.nan_to_num(a, nan=0))

[10. 20. 30.  0. 50.]


In [38]:
a = np.array([10, 20, 30, np.nan, 50])
print(np.nan_to_num(a, nan=100))

[ 10.  20.  30. 100.  50.]


In [39]:
a = np.array([
    [10, 20, np.nan],
    [40, np.nan, np.nan]
])

print(np.nan_to_num(a, nan=100))

[[ 10.  20. 100.]
 [ 40. 100. 100.]]


In [40]:
a = np.array([
    [10, 20, np.nan],
    [40, np.nan, np.nan]
])

print(np.nan_to_num(a, nan=0))

[[10. 20.  0.]
 [40.  0.  0.]]
