# Day 24/180 — Advanced Indexing & Broadcasting

1. Advanced Indexing
   - Fancy Indexing
   - Boolean Indexing

2. Broadcasting
   - Scalar broadcasting
   - Broadcasting between arrays
   - Broadcasting rules
   - Shape compatibility

# Fancy Indexing

Fancy indexing means we have to select the specific elements from a NumPy array using
a list or NumPy array of indices.

Unlike slicing, the indices do not have to be continuous.

Example: arr[[0, 3, 6]]

Means:
- select index 0
- select index 3
- select index 6

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[0, 2, 4]])

[1 3 5]


In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[[0, 3, 6]])

[1 4 7]


### Normal Indexing vs Slicing vs Fancy Indexing

Normal indexing selects one element.

Slicing selects a continuous range.

Fancy indexing selects specific positions.

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[2])        # Normal indexing
print(arr[1:4])      # Slicing
print(arr[[1, 3, 4]])  # Fancy indexing

3
[2 3 4]
[2 4 5]


Major benefit of fancy indexing is that the selected indices
do not need to be next to each other.

In [5]:
arr = np.array([10, 20, 30, 40, 50, 60])
result = arr[[0, 3, 5]]
print(result)

[10 40 60]


In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])
result = arr[[0, 2, 5]]
print(result)

[10 30 60]


### Repeating Indices

Fancy indexing allows us to select the same index multiple times.

The result will contain the value multiple times.

In [7]:
arr = np.array([10, 20, 30, 40])
print(arr[[1, 1, 3, 1]])

[20 20 40 20]


In [8]:
arr = np.array([10, 20, 30, 40])
print(arr[[0, 1, 1, 1, 3]])

[10 20 20 20 40]


In [9]:
# negative indexing

arr = np.array([10, 20, 30, 40, 50])
print(arr[[-1, -3, 0]])

[50 30 10]


In [10]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[[-1, -3, -3, -4, -5, 0]])

[5 3 3 2 1 1]


In a 2D array, fancy indexing can be used to select specific rows.

In [11]:
# Fancy indexing in 2D array

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[[0, 2]])

[[10 20 30]
 [70 80 90]]


Fancy indexing does not have to follow the original order. We can select rows in any order.

In [12]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
print(arr[[2, 0, 1]])

[[70 80 90]
 [10 20 30]
 [40 50 60]]


In [13]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(arr[[2, 0, 1]])

[[7 8 9]
 [1 2 3]
 [4 5 6]]


### Selecting Specific Row and Column Positions

We can provide two index arrays:

- one for rows
- one for columns

NumPy pairs them together.

Example:

arr[[0, 1, 2], [2, 1, 0]]

means:

arr[0, 2]

arr[1, 1]

arr[2, 0]

In [14]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])                                  
                                   #[0, 1, 2] = rows, [2, 1, 0] = columns
print(arr[[0, 1, 2], [2, 1, 0]])   # pairs (0, 2)  (1, 1)  (2, 0)

[30 50 70]


### Fancy Indexing vs Slicing in 2D

Slicing usually selects a rectangular section of an array.

Fancy indexing with row and column arrays selects specific
row-column pairs.

In [15]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[0:2, 1:3])    #slicing

print()

print(arr[[0, 1], [1, 2]])

[[20 30]
 [50 60]]

[20 60]


##  np.ix_()

np.ix_() can be used when we want combinations of selected rows
and columns.

It produces a rectangular result.

In [16]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[np.ix_([0, 2], [1, 2])])

[[20 30]
 [80 90]]


# Boolean Indexing

Boolean indexing means selecting elements based on a condition.

The condition produces a Boolean array containing:

True
False

NumPy keeps the elements where the condition is True.

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr > 25)

[False False  True  True  True]


In [18]:
print(arr[arr > 25])  #means select all values that are greater than 25.

[30 40 50]


In [19]:
print(arr[arr < 35])

[10 20 30]


In [20]:
print(arr[arr <= 35])

[10 20 30]


In [21]:
print(arr[arr >= 30])

[30 40 50]


In [22]:
print(arr[arr == 20])

[20]


In [23]:
print(arr[arr != 20])

[10 30 40 50]


In [24]:
# with AND

print(arr[arr == 20])

[20]


In [25]:
# with OR

print(arr[(arr < 20) | (arr > 40)])

[10 50]


## 23. Boolean Indexing in a 2D Array

When we select values from a 2D array using a Boolean condition,
the selected values are returned as a 1D array.

In [26]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr[arr > 50])

[60 70 80 90]


In [27]:
print(arr[arr < 50])

[10 20 30 40]


We can store the condition in a variable. This Boolean array is called a **Boolean mask.**

The mask tells NumPy which elements should be selected.

In [28]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

mask = arr > 50
print(mask)

[[False False False]
 [False False  True]
 [ True  True  True]]


In [29]:
print(arr[mask])

[60 70 80 90]


We can also change values through boolean indexing.

In [30]:
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 30] = 0
print(arr)

[10 20 30  0  0]


In [31]:
arr = np.array([-5, 10, -2, 20, -8])
arr[arr < 0] = 0
print(arr)

[ 0 10  0 20  0]


In [32]:
arr = np.array([-5, -10, -2, 20, -8])
arr[arr < 0] = 0
print(arr)

[ 0  0  0 20  0]


## Boolean Indexing with np.isnan()

np.isnan() checks whether values are NaN.

It returns True where the value is NaN.

This can be useful when cleaning missing data.

In [33]:
arr = np.array([10, np.nan, 30, np.nan, 50])
print(np.isnan(arr))

[False  True False  True False]


In [34]:
print(arr[np.isnan(arr)])

[nan nan]


## Combining Fancy Indexing and Boolean Indexing

Fancy indexing can first select specific elements.

Boolean indexing can then filter those selected elements.

This allows us to perform more specific data selection.

In [35]:
arr = np.array([10, 20, 30, 40, 50])
selected = arr[[0, 2, 4]]
print(selected)
print(selected[selected > 20])

[10 30 50]
[30 50]


# Broadcasting

Broadcasting is a NumPy feature that allows arithmetic operations
between arrays with different shapes.

NumPy automatically expands the smaller array conceptually so that
the shapes become compatible.

Broadcasting can be used with:

- addition
- subtraction
- multiplication
- division
- power

and many NumPy functions.

## Scalar Broadcasting

A scalar is a single value.

When a scalar is used with an array, NumPy applies that value
to every element of the array.

In [36]:
arr = np.array([10, 20, 30, 50])

print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr / 5)

[15 25 35 55]
[ 5 15 25 45]
[ 50 100 150 250]
[ 2.  4.  6. 10.]


In [37]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [38]:
print(arr - 10)

[[-9 -8 -7]
 [-6 -5 -4]]


In [39]:
print(arr / 10)

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [40]:
print(arr ** 10)

[[       1     1024    59049]
 [ 1048576  9765625 60466176]]


## Broadcasting Rules

NumPy compares array dimensions from right to left.

Two dimensions are compatible when:

1. They are equal, OR
2. One of them is 1.

If the dimensions do not satisfy either rule, broadcasting fails.

In [41]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(a + b)

[[11 22 33]
 [44 55 66]]


In [42]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([10, 20, 30])

print(a + b)

[[11 22 33]
 [14 25 36]]


## Important

The shape of an array tells us its dimensions.

Understanding shape is very important when working with broadcasting.

In [43]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([10, 20, 30])

In [44]:
print(a.shape)
print(b.shape)

(2, 3)
(3,)


## Row Vector vs 1D Array

These two arrays may look similar when printed, but their shapes
are different.

[1, 2, 3] has shape (3,)

[[1, 2, 3]] has shape (1, 3)

In [45]:
a = np.array([1, 2, 3])

b = np.array([[1, 2, 3]])

print(a)
print(a.shape)

print()

print(b)
print(b.shape)

[1 2 3]
(3,)

[[1 2 3]]
(1, 3)


## Understanding Column Broadcasting

The column:

[1]

[2]

[3]

is conceptually combined with:

[10 20 30]

The result becomes:

[11 21 31]

[12 22 32]

[13 23 33]

In [46]:
a = np.array([
    [1],
    [2],
    [3]
])

b = np.array([10, 20, 30])

result = a + b
print(result)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [47]:
temperatures = np.array([
    [30, 32, 35],
    [28, 31, 33]
])

print(temperatures - 2)

[[28 30 33]
 [26 29 31]]


In [48]:
temperatures = np.array([
    [30, 32, 35],
    [28, 31, 33]
])

print(temperatures + 2)

[[32 34 37]
 [30 33 35]]


In [49]:
numbers = np.array([
    [50, 60, 70],
    [80, 90, 100]
])

print(numbers / 100)

[[0.5 0.6 0.7]
 [0.8 0.9 1. ]]


## Broadcasting with Different Values for Each Column

A 1D array can be broadcast across the rows.

Here each column receives a different value.

In [50]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

bonus = np.array([1, 2, 3])

print(data + bonus)

[[11 22 33]
 [41 52 63]]


In [51]:
data = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

means = np.mean(data, axis=0)

print(means)
print(means.shape)

[20. 30. 40.]
(3,)
